apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See: https://github.com/kubernetes-sigs/kustomize/issues/1301#issuecomment-744460286
namespace: rusty-containers

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "0.1.0"

resources:
  - ../../base
  - ingress/simple-api.yaml
