apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  labels:
    app.kubernetes.io/component: simple-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: simple-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: simple-api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: simple-api
          image: simple-api:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
            initialDelaySeconds: 2
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: simple-api-config
          # env:
          resources:
            requests:
              cpu: 50m
              memory: 10M
            limits:
              cpu: 500m
              memory: 50M
          securityContext:
            allowPrivilegeEscalation: false
