apiVersion: v1
kind: Service
metadata:
  name: simple-api
  labels:
    app.kubernetes.io/component: simple-api
spec:
  selector:
    app.kubernetes.io/component: simple-api
  ports:
    - name: http
      port: 8080
      targetPort: http
